Added fallback method select container by name
microsoft/ApplicationInsights-Kubernetes pull request #347
Opened 2023-03-29 05:46 UTC by TTmaister

Proposal #344 

Fallback method if container id has not provided.

Read ContainerName environment variable and find first container by name

2023-03-29 05:54 UTC, TTmaister commented
@microsoft-github-policy-service agree

2023-03-29 19:55 UTC, xiaomi7732 requested changes
Thanks for the contribution. It largely looks good to me. There's only one small piece about null handling, do you mind taking a look? (y)

2023-03-30 05:06 UTC, TTmaister commented on src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
> +                containerStatus = containerStatuses.FirstOrDefault(c => c.Name == containerName);
Changed to string equals.

2023-03-30 05:09 UTC, TTmaister commented on src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
> +                containerStatus = containerStatuses.FirstOrDefault(c => c.Name == containerName);
Added check that `containerStatus` is not null.

2023-03-30 05:10 UTC, TTmaister commented on src/ApplicationInsights.Kubernetes/Containers/ContainerIdHolder.cs
>              using (IServiceScope scope = _serviceScopeFactory.CreateScope())
Also check that `containerStatus` is not null.

2023-03-30 18:00 UTC, xiaomi7732 approved these changes

2023-03-30 18:00 UTC, merged